# Use the official OpenJDK image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the target directory to the container
COPY target/jopPortal-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port (default Spring Boot port)
EXPOSE 8080

# Set environment variables for MongoDB URI (pass at runtime)
ENV MONGO_URI=""

# Run the JAR file using the provided MongoDB URI
CMD ["sh", "-c", "java -Dspring.data.mongodb.uri=$MONGO_URI -jar app.jar"]
