FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the JAR file to the container
COPY target/JopPortal-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application without Mongo URI from the environment
CMD ["java", "-jar", "app.jar"]
