# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file to the container
COPY target/jopPortal-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 5000

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
